version: '3.1'

services:
  database:
    image: postgres:12.3
    volumes:
    - ./postgres-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_MULTIPLE_DATABASES: cats,dogs
    ports:
      - 5432:5432
